serial_key_id = 'in.roxfort.app.zwing.vendor:id/input_edittext'
authenticate_button = '//android.widget.LinearLayout[@resource-id="in.roxfort.app.zwing.vendor:id/btn_authenticate"]'
username_field = '//android.widget.EditText[@resource-id="in.roxfort.app.zwing.vendor:id/input_edittext" and @text="Enter Phone Number/Username/Email"]'
pin_field = '//android.widget.EditText[@resource-id="in.roxfort.app.zwing.vendor:id/input_edittext" and @text="Enter PIN"]'
entered_pin_field = '//android.widget.EditText[@resource-id="in.roxfort.app.zwing.vendor:id/input_edittext" and @text="123456"]'
login_button = '//android.widget.LinearLayout[@resource-id="in.roxfort.app.zwing.vendor:id/btn_login"]'
homepage_heading_id = 'in.roxfort.app.zwing.vendor:id/tv_heading'

catalog_button_id = 'in.roxfort.app.zwing.vendor:id/img_catalog'
search_product_button_id = 'in.roxfort.app.zwing.vendor:id/search_product'
search_product_field_id = 'in.roxfort.app.zwing.vendor:id/search_txt'
add_product_button_id = 'in.roxfort.app.zwing.vendor:id/txt_qty'
go_to_cart_button = '//android.widget.LinearLayout[@resource-id="in.roxfort.app.zwing.vendor:id/goToCart"]/android.widget.LinearLayout'
product_name_id = 'in.roxfort.app.zwing.vendor:id/txt_item_name'

tag_customer_button_id = 'in.roxfort.app.zwing.vendor:id/img_tag_customer'
add_new_customer_button_id = 'in.roxfort.app.zwing.vendor:id/rel_add_new_cust'
search_customer_field_id = 'in.roxfort.app.zwing.vendor:id/edt_search'
searched_customer = '//android.widget.TextView[@resource-id="in.roxfort.app.zwing.vendor:id/txt_customer_name" and @text="value"]'
search_button_id = 'in.roxfort.app.zwing.vendor:id/btn_continue'
add_to_bill_button_id = 'in.roxfort.app.zwing.vendor:id/img_edit'
tagged_customer_name_id = 'in.roxfort.app.zwing.vendor:id/txt_customer_name'

checkout_button_id = 'in.roxfort.app.zwing.vendor:id/btn_checkout'
cash_option = '//android.widget.TextView[@resource-id="in.roxfort.app.zwing.vendor:id/txt_payment_type" and @text="Cash"]'
gpay_option = '//android.widget.TextView[@resource-id="in.roxfort.app.zwing.vendor:id/txt_payment_type" and @text="Gpay"]'
collect_cash_title = '//android.widget.TextView[@resource-id="in.roxfort.app.zwing.vendor:id/txt_title" and @text="Collect Cash"]'
customer_paid_amount = 'in.roxfort.app.zwing.vendor:id/edt_amount'
collect_button = 'in.roxfort.app.zwing.vendor:id/btn_continue'
payable_amount = 'in.roxfort.app.zwing.vendor:id/amount_txt'
payment_success_screen = 'in.roxfort.app.zwing.vendor:id/txt_payment_success_type'
invoice_number_id = 'in.roxfort.app.zwing.vendor:id/txt_invoice_id'
continue_button = 'in.roxfort.app.zwing.vendor:id/btn_collect_cash'
edit_payable_amount = 'in.roxfort.app.zwing.vendor:id/edt_payable_amount'
home_button = 'in.roxfort.app.zwing.vendor:id/btn_home'
hamberger_menu_id = 'in.roxfort.app.zwing.vendor:id/iv_left_arrow'
transaction_option = '(//android.widget.RelativeLayout[@resource-id="in.roxfort.app.zwing.vendor:id/layout_bg"])[2]'
invoices_option = '//android.widget.TextView[@resource-id="in.roxfort.app.zwing.vendor:id/posNameId" and @text="Invoices"]'
invoice_search_button  = 'in.roxfort.app.zwing.vendor:id/img_search'
invoice_search_field_id = 'in.roxfort.app.zwing.vendor:id/search_src_text'

logout_button_id = 'in.roxfort.app.zwing.vendor:id/logout_btn'
close_session_button_id = '//android.widget.TextView[@resource-id="in.roxfort.app.zwing.vendor:id/tv_btn_text_right" and @text="Close Session"]'
closing_balance_field = 'in.roxfort.app.zwing.vendor:id/edt_bal'
yes_logout_button_id = 'in.roxfort.app.zwing.vendor:id/btn_positive'
swipe_to_close_arrow = '//android.widget.RelativeLayout[@resource-id="in.roxfort.app.zwing.vendor:id/swipeBtn"]/android.widget.ImageView'
session_close_done_button = 'in.roxfort.app.zwing.vendor:id/btn_done'

open_session_screen_heading = '//android.widget.TextView[@resource-id="in.roxfort.app.zwing.vendor:id/tv_heading" and @text="Open Session"]'
opening_balance_field = 'in.roxfort.app.zwing.vendor:id/edt_bal'
swipe_to_open_arrow = '//android.widget.RelativeLayout[@resource-id="in.roxfort.app.zwing.vendor:id/swipeBtn"]/android.widget.ImageView'

kebab_menu_id = 'in.roxfort.app.zwing.vendor:id/img_menu_icon'
clear_cart_button_id = '(//android.view.View[@resource-id="in.roxfort.app.zwing.vendor:id/view_top"])[7]'


add_items_from_previous_session_heading = '//android.widget.TextView[@resource-id="in.roxfort.app.zwing.vendor:id/txt_title" and @text="Add items from previous session?"]'
discard_items_button = '//android.widget.TextView[@resource-id="in.roxfort.app.zwing.vendor:id/tv_btn_text_left" and @text="Discard Items"]'

bill_discount_button = 'in.roxfort.app.zwing.vendor:id/btn_bill_discount'
custom_discount_button = '//android.widget.LinearLayout[@content-desc="Custom Discount"]'
discount_value_field = 'in.roxfort.app.zwing.vendor:id/edt_discount_value'
apply_discount_button = 'in.roxfort.app.zwing.vendor:id/btn_apply_discount'
payable_amount_split = '(//android.widget.TextView[@resource-id="in.roxfort.app.zwing.vendor:id/txt_amount"])[1]'
payment_summary_icon = 'in.roxfort.app.zwing.vendor:id/img_payment_summary'

go_back_arrow = 'in.roxfort.app.zwing.vendor:id/img_back'
hide_button = 'in.roxfort.app.zwing.vendor:id/btn_hide'